### ISSUE TITLE
Feature Request - Option to change gamemode to spectator for limbo world

### ISSUE THREAD

**Issue by RalphORama** [Elytrium/LimboReconnect#13]
First off, this plugin was exactly what I was looking for! Thanks very much for creating it 😁

 I think the ability to put players into spectator would be a good addition to this plugin - mainly, it would hide the UI and hand of the playermodel, making the experience feel somewhat cleaner in my opinion (see attached screenshots).

The config option could be something like:

```yaml
world:
  # Dimensions: OVERWORLD, NETHER, THE_END
  dimension: "THE_END"
  # Gamemodes: SURVIVAL, CREATIVE, SPECTATOR, ADVENTURE
  gamemode: "SPECTATOR"
  # Load world from file
  # etc...
```

### Before

![2023-06-22_11 10 14](https://github.com/Elytrium/LimboReconnect/assets/6566104/c4999892-3d0b-48a7-b0b0-60a02de7a389)

### After

![2023-06-22_11 10 14_mod](https://github.com/Elytrium/LimboReconnect/assets/6566104/6e8b83eb-1885-4626-92ec-405e87524a5c)
